<?php
  function getCountries()
  {
  	$countryArray =array(
				  		array('sort_name'=>'AD', 'name'=>'ANDORRA','code'=>'376'),
						array('sort_name'=>'AE', 'name'=>'UNITED ARAB EMIRATES','code'=>'971'),
						array('sort_name'=>'AF', 'name'=>'AFGHANISTAN','code'=>'93'),
						array('sort_name'=>'AG', 'name'=>'ANTIGUA AND BARBUDA','code'=>'1268'),
						array('sort_name'=>'AI', 'name'=>'ANGUILLA','code'=>'1264'),
						array('sort_name'=>'AL', 'name'=>'ALBANIA','code'=>'355'),
						array('sort_name'=>'AM', 'name'=>'ARMENIA','code'=>'374'),

		array('sort_name'=>'AN', 'name'=>'NETHERLANDS ANTILLES','code'=>'599'),
		array('sort_name'=>'AO', 'name'=>'ANGOLA','code'=>'244'),
		array('sort_name'=>'AQ', 'name'=>'ANTARCTICA','code'=>'672'),
		array('sort_name'=>'AR', 'name'=>'ARGENTINA','code'=>'54'),
		array('sort_name'=>'AS', 'name'=>'AMERICAN SAMOA','code'=>'1684'),
		array('sort_name'=>'AT', 'name'=>'AUSTRIA','code'=>'43'),
		array('sort_name'=>'AU', 'name'=>'AUSTRALIA','code'=>'61'),
		array('sort_name'=>'AW', 'name'=>'ARUBA','code'=>'297'),
		array('sort_name'=>'AZ', 'name'=>'AZERBAIJAN','code'=>'994'),
		array('sort_name'=>'BA', 'name'=>'BOSNIA AND HERZEGOVINA','code'=>'387'),
		array('sort_name'=>'BB', 'name'=>'BARBADOS','code'=>'1246'),
		array('sort_name'=>'BD', 'name'=>'BANGLADESH','code'=>'880'),
		array('sort_name'=>'BE', 'name'=>'BELGIUM','code'=>'32'),
		array('sort_name'=>'BF', 'name'=>'BURKINA FASO','code'=>'226'),
		array('sort_name'=>'BG', 'name'=>'BULGARIA','code'=>'359'),
		array('sort_name'=>'BH', 'name'=>'BAHRAIN','code'=>'973'),
		array('sort_name'=>'BI', 'name'=>'BURUNDI','code'=>'257'),
		array('sort_name'=>'BJ', 'name'=>'BENIN','code'=>'229'),
		array('sort_name'=>'BL', 'name'=>'SAINT BARTHELEMY','code'=>'590'),
		array('sort_name'=>'BM', 'name'=>'BERMUDA','code'=>'1441'),
		array('sort_name'=>'BN', 'name'=>'BRUNEI DARUSSALAM','code'=>'673'),
		array('sort_name'=>'BO', 'name'=>'BOLIVIA','code'=>'591'),
		array('sort_name'=>'BR', 'name'=>'BRAZIL','code'=>'55'),
		array('sort_name'=>'BS', 'name'=>'BAHAMAS','code'=>'1242'),
		array('sort_name'=>'BT', 'name'=>'BHUTAN','code'=>'975'),
		array('sort_name'=>'BW', 'name'=>'BOTSWANA','code'=>'267'),
		array('sort_name'=>'BY', 'name'=>'BELARUS','code'=>'375'),
		array('sort_name'=>'BZ', 'name'=>'BELIZE','code'=>'501'),
		array('sort_name'=>'CA', 'name'=>'CANADA','code'=>'1'),
		array('sort_name'=>'CC', 'name'=>'COCOS (KEELING) ISLANDS','code'=>'61'),
		array('sort_name'=>'CD', 'name'=>'CONGO, THE DEMOCRATIC REPUBLIC OF THE','code'=>'243'),
		array('sort_name'=>'CF', 'name'=>'CENTRAL AFRICAN REPUBLIC','code'=>'236'),
		array('sort_name'=>'CG', 'name'=>'CONGO','code'=>'242'),
		array('sort_name'=>'CH', 'name'=>'SWITZERLAND','code'=>'41'),
		array('sort_name'=>'CI', 'name'=>'COTE D IVOIRE','code'=>'225'),
		array('sort_name'=>'CK', 'name'=>'COOK ISLANDS','code'=>'682'),
		array('sort_name'=>'CL', 'name'=>'CHILE','code'=>'56'),
		array('sort_name'=>'CM', 'name'=>'CAMEROON','code'=>'237'),
		array('sort_name'=>'CN', 'name'=>'CHINA','code'=>'86'),
		array('sort_name'=>'CO', 'name'=>'COLOMBIA','code'=>'57'),
		array('sort_name'=>'CR', 'name'=>'COSTA RICA','code'=>'506'),
		array('sort_name'=>'CU', 'name'=>'CUBA','code'=>'53'),
		array('sort_name'=>'CV', 'name'=>'CAPE VERDE','code'=>'238'),
		array('sort_name'=>'CX', 'name'=>'CHRISTMAS ISLAND','code'=>'61'),
		array('sort_name'=>'CY', 'name'=>'CYPRUS','code'=>'357'),
		array('sort_name'=>'CZ', 'name'=>'CZECH REPUBLIC','code'=>'420'),
		array('sort_name'=>'DE', 'name'=>'GERMANY','code'=>'49'),
		array('sort_name'=>'DJ', 'name'=>'DJIBOUTI','code'=>'253'),
		array('sort_name'=>'DK', 'name'=>'DENMARK','code'=>'45'),
		array('sort_name'=>'DM', 'name'=>'DOMINICA','code'=>'1767'),
		array('sort_name'=>'DO', 'name'=>'DOMINICAN REPUBLIC','code'=>'1809'),
		array('sort_name'=>'DZ', 'name'=>'ALGERIA','code'=>'213'),
		array('sort_name'=>'EC', 'name'=>'ECUADOR','code'=>'593'),
		array('sort_name'=>'EE', 'name'=>'ESTONIA','code'=>'372'),
		array('sort_name'=>'EG', 'name'=>'EGYPT','code'=>'20'),
		array('sort_name'=>'ER', 'name'=>'ERITREA','code'=>'291'),
		array('sort_name'=>'ES', 'name'=>'SPAIN','code'=>'34'),
		array('sort_name'=>'ET', 'name'=>'ETHIOPIA','code'=>'251'),
		array('sort_name'=>'FI', 'name'=>'FINLAND','code'=>'358'),
		array('sort_name'=>'FJ', 'name'=>'FIJI','code'=>'679'),
		array('sort_name'=>'FK', 'name'=>'FALKLAND ISLANDS (MALVINAS)','code'=>'500'),
		array('sort_name'=>'FM', 'name'=>'MICRONESIA, FEDERATED STATES OF','code'=>'691'),
		array('sort_name'=>'FO', 'name'=>'FAROE ISLANDS','code'=>'298'),
		array('sort_name'=>'FR', 'name'=>'FRANCE','code'=>'33'),
		array('sort_name'=>'GA', 'name'=>'GABON','code'=>'241'),
		array('sort_name'=>'GB', 'name'=>'UNITED KINGDOM','code'=>'44'),
		array('sort_name'=>'GD', 'name'=>'GRENADA','code'=>'1473'),
		array('sort_name'=>'GE', 'name'=>'GEORGIA','code'=>'995'),
		array('sort_name'=>'GH', 'name'=>'GHANA','code'=>'233'),
		array('sort_name'=>'GI', 'name'=>'GIBRALTAR','code'=>'350'),
		array('sort_name'=>'GL', 'name'=>'GREENLAND','code'=>'299'),
		array('sort_name'=>'GM', 'name'=>'GAMBIA','code'=>'220'),
		array('sort_name'=>'GN', 'name'=>'GUINEA','code'=>'224'),
		array('sort_name'=>'GQ', 'name'=>'EQUATORIAL GUINEA','code'=>'240'),
		array('sort_name'=>'GR', 'name'=>'GREECE','code'=>'30'),
		array('sort_name'=>'GT', 'name'=>'GUATEMALA','code'=>'502'),
		array('sort_name'=>'GU', 'name'=>'GUAM','code'=>'1671'),
		array('sort_name'=>'GW', 'name'=>'GUINEA-BISSAU','code'=>'245'),
		array('sort_name'=>'GY', 'name'=>'GUYANA','code'=>'592'),
		array('sort_name'=>'HK', 'name'=>'HONG KONG','code'=>'852'),
		array('sort_name'=>'HN', 'name'=>'HONDURAS','code'=>'504'),
		array('sort_name'=>'HR', 'name'=>'CROATIA','code'=>'385'),
		array('sort_name'=>'HT', 'name'=>'HAITI','code'=>'509'),
		array('sort_name'=>'HU', 'name'=>'HUNGARY','code'=>'36'),
		array('sort_name'=>'ID', 'name'=>'INDONESIA','code'=>'62'),
		array('sort_name'=>'IE', 'name'=>'IRELAND','code'=>'353'),
		array('sort_name'=>'IL', 'name'=>'ISRAEL','code'=>'972'),
		array('sort_name'=>'IM', 'name'=>'ISLE OF MAN','code'=>'44'),
		array('sort_name'=>'IN', 'name'=>'INDIA','code'=>'91'),
		array('sort_name'=>'IQ', 'name'=>'IRAQ','code'=>'964'),
		array('sort_name'=>'IR', 'name'=>'IRAN, ISLAMIC REPUBLIC OF','code'=>'98'),
		array('sort_name'=>'IS', 'name'=>'ICELAND','code'=>'354'),
		array('sort_name'=>'IT', 'name'=>'ITALY','code'=>'39'),
		array('sort_name'=>'JM', 'name'=>'JAMAICA','code'=>'1876'),
		array('sort_name'=>'JO', 'name'=>'JORDAN','code'=>'962'),
		array('sort_name'=>'JP', 'name'=>'JAPAN','code'=>'81'),
		array('sort_name'=>'KE', 'name'=>'KENYA','code'=>'254'),
		array('sort_name'=>'KG', 'name'=>'KYRGYZSTAN','code'=>'996'),
		array('sort_name'=>'KH', 'name'=>'CAMBODIA','code'=>'855'),
		array('sort_name'=>'KI', 'name'=>'KIRIBATI','code'=>'686'),
		array('sort_name'=>'KM', 'name'=>'COMOROS','code'=>'269'),

		array('sort_name'=>'KN', 'name'=>'SAINT KITTS AND NEVIS','code'=>'1869'),
		array('sort_name'=>'KP', 'name'=>'KOREA DEMOCRATIC PEOPLES REPUBLIC OF','code'=>'850'),
		array('sort_name'=>'KR', 'name'=>'KOREA REPUBLIC OF','code'=>'82'),
		array('sort_name'=>'KW', 'name'=>'KUWAIT','code'=>'965'),
		array('sort_name'=>'KY', 'name'=>'CAYMAN ISLANDS','code'=>'1345'),
		array('sort_name'=>'KZ', 'name'=>'KAZAKSTAN','code'=>'7'),
		array('sort_name'=>'LA', 'name'=>'LAO PEOPLES DEMOCRATIC REPUBLIC','code'=>'856'),
		array('sort_name'=>'LB', 'name'=>'LEBANON','code'=>'961'),
		array('sort_name'=>'LC', 'name'=>'SAINT LUCIA','code'=>'1758'),
		array('sort_name'=>'LI', 'name'=>'LIECHTENSTEIN','code'=>'423'),
		array('sort_name'=>'LK', 'name'=>'SRI LANKA','code'=>'94'),
		array('sort_name'=>'LR', 'name'=>'LIBERIA','code'=>'231'),
		array('sort_name'=>'LS', 'name'=>'LESOTHO','code'=>'266'),
		array('sort_name'=>'LT', 'name'=>'LITHUANIA','code'=>'370'),
		array('sort_name'=>'LU', 'name'=>'LUXEMBOURG','code'=>'352'),
		array('sort_name'=>'LV', 'name'=>'LATVIA','code'=>'371'),
		array('sort_name'=>'LY', 'name'=>'LIBYAN ARAB JAMAHIRIYA','code'=>'218'),
		array('sort_name'=>'MA', 'name'=>'MOROCCO','code'=>'212'),
		array('sort_name'=>'MC', 'name'=>'MONACO','code'=>'377'),
		array('sort_name'=>'MD', 'name'=>'MOLDOVA, REPUBLIC OF','code'=>'373'),
		array('sort_name'=>'ME', 'name'=>'MONTENEGRO','code'=>'382'),
		array('sort_name'=>'MF', 'name'=>'SAINT MARTIN','code'=>'1599'),
		array('sort_name'=>'MG', 'name'=>'MADAGASCAR','code'=>'261'),
		array('sort_name'=>'MH', 'name'=>'MARSHALL ISLANDS','code'=>'692'),
		array('sort_name'=>'MK', 'name'=>'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','code'=>'389'),
		array('sort_name'=>'ML', 'name'=>'MALI','code'=>'223'),
		array('sort_name'=>'MM', 'name'=>'MYANMAR','code'=>'95'),
		array('sort_name'=>'MN', 'name'=>'MONGOLIA','code'=>'976'),
		array('sort_name'=>'MO', 'name'=>'MACAU','code'=>'853'),
		array('sort_name'=>'MP', 'name'=>'NORTHERN MARIANA ISLANDS','code'=>'1670'),
		array('sort_name'=>'MR', 'name'=>'MAURITANIA','code'=>'222'),
		array('sort_name'=>'MS', 'name'=>'MONTSERRAT','code'=>'1664'),
		array('sort_name'=>'MT', 'name'=>'MALTA','code'=>'356'),
		array('sort_name'=>'MU', 'name'=>'MAURITIUS','code'=>'230'),
		array('sort_name'=>'MV', 'name'=>'MALDIVES','code'=>'960'),
		array('sort_name'=>'MW', 'name'=>'MALAWI','code'=>'265'),
		array('sort_name'=>'MX', 'name'=>'MEXICO','code'=>'52'),
		array('sort_name'=>'MY', 'name'=>'MALAYSIA','code'=>'60'),
		array('sort_name'=>'MZ', 'name'=>'MOZAMBIQUE','code'=>'258'),
		array('sort_name'=>'NA', 'name'=>'NAMIBIA','code'=>'264'),
		array('sort_name'=>'NC', 'name'=>'NEW CALEDONIA','code'=>'687'),
		array('sort_name'=>'NE', 'name'=>'NIGER','code'=>'227'),
		array('sort_name'=>'NG', 'name'=>'NIGERIA','code'=>'234'),
		array('sort_name'=>'NI', 'name'=>'NICARAGUA','code'=>'505'),
		array('sort_name'=>'NL', 'name'=>'NETHERLANDS','code'=>'31'),
		array('sort_name'=>'NO', 'name'=>'NORWAY','code'=>'47'),
		array('sort_name'=>'NP', 'name'=>'NEPAL','code'=>'977'),
		array('sort_name'=>'NR', 'name'=>'NAURU','code'=>'674'),
		array('sort_name'=>'NU', 'name'=>'NIUE','code'=>'683'),
		array('sort_name'=>'NZ', 'name'=>'NEW ZEALAND','code'=>'64'),
		array('sort_name'=>'OM', 'name'=>'OMAN','code'=>'968'),
		array('sort_name'=>'PA', 'name'=>'PANAMA','code'=>'507'),
		array('sort_name'=>'PE', 'name'=>'PERU','code'=>'51'),
		array('sort_name'=>'PF', 'name'=>'FRENCH POLYNESIA','code'=>'689'),
		array('sort_name'=>'PG', 'name'=>'PAPUA NEW GUINEA','code'=>'675'),
		array('sort_name'=>'PH', 'name'=>'PHILIPPINES','code'=>'63'),
		array('sort_name'=>'PK', 'name'=>'PAKISTAN','code'=>'92'),
		array('sort_name'=>'PL', 'name'=>'POLAND','code'=>'48'),
		array('sort_name'=>'PM', 'name'=>'SAINT PIERRE AND MIQUELON','code'=>'508'),
		array('sort_name'=>'PN', 'name'=>'PITCAIRN','code'=>'870'),
		array('sort_name'=>'PR', 'name'=>'PUERTO RICO','code'=>'1'),
		array('sort_name'=>'PT', 'name'=>'PORTUGAL','code'=>'351'),
		array('sort_name'=>'PW', 'name'=>'PALAU','code'=>'680'),
		array('sort_name'=>'PY', 'name'=>'PARAGUAY','code'=>'595'),
		array('sort_name'=>'QA', 'name'=>'QATAR','code'=>'974'),
		array('sort_name'=>'RO', 'name'=>'ROMANIA','code'=>'40'),
		array('sort_name'=>'RS', 'name'=>'SERBIA','code'=>'381'),
		array('sort_name'=>'RU', 'name'=>'RUSSIAN FEDERATION','code'=>'7'),
		array('sort_name'=>'RW', 'name'=>'RWANDA','code'=>'250'),
		array('sort_name'=>'SA', 'name'=>'SAUDI ARABIA','code'=>'966'),
		array('sort_name'=>'SB', 'name'=>'SOLOMON ISLANDS','code'=>'677'),
		array('sort_name'=>'SC', 'name'=>'SEYCHELLES','code'=>'248'),
		array('sort_name'=>'SD', 'name'=>'SUDAN','code'=>'249'),
		array('sort_name'=>'SE', 'name'=>'SWEDEN','code'=>'46'),
		array('sort_name'=>'SG', 'name'=>'SINGAPORE','code'=>'65'),
		array('sort_name'=>'SH', 'name'=>'SAINT HELENA','code'=>'290'),
		array('sort_name'=>'SI', 'name'=>'SLOVENIA','code'=>'386'),
		array('sort_name'=>'SK', 'name'=>'SLOVAKIA','code'=>'421'),
		array('sort_name'=>'SL', 'name'=>'SIERRA LEONE','code'=>'232'),
		array('sort_name'=>'SM', 'name'=>'SAN MARINO','code'=>'378'),
		array('sort_name'=>'SN', 'name'=>'SENEGAL','code'=>'221'),
		array('sort_name'=>'SO', 'name'=>'SOMALIA','code'=>'252'),
		array('sort_name'=>'SR', 'name'=>'SURINAME','code'=>'597'),
		array('sort_name'=>'ST', 'name'=>'SAO TOME AND PRINCIPE','code'=>'239'),
		array('sort_name'=>'SV', 'name'=>'EL SALVADOR','code'=>'503'),
		array('sort_name'=>'SY', 'name'=>'SYRIAN ARAB REPUBLIC','code'=>'963'),
		array('sort_name'=>'SZ', 'name'=>'SWAZILAND','code'=>'268'),
		array('sort_name'=>'TC', 'name'=>'TURKS AND CAICOS ISLANDS','code'=>'1649'),
		array('sort_name'=>'TD', 'name'=>'CHAD','code'=>'235'),
		array('sort_name'=>'TG', 'name'=>'TOGO','code'=>'228'),
		array('sort_name'=>'TH', 'name'=>'THAILAND','code'=>'66'),
		array('sort_name'=>'TJ', 'name'=>'TAJIKISTAN','code'=>'992'),
		array('sort_name'=>'TK', 'name'=>'TOKELAU','code'=>'690'),
		array('sort_name'=>'TL', 'name'=>'TIMOR-LESTE','code'=>'670'),
		array('sort_name'=>'TM', 'name'=>'TURKMENISTAN','code'=>'993'),
		array('sort_name'=>'TN', 'name'=>'TUNISIA','code'=>'216'),
		array('sort_name'=>'TO', 'name'=>'TONGA','code'=>'676'),
		array('sort_name'=>'TR', 'name'=>'TURKEY','code'=>'90'),
		array('sort_name'=>'TT', 'name'=>'TRINIDAD AND TOBAGO','code'=>'1868'),
		array('sort_name'=>'TV', 'name'=>'TUVALU','code'=>'688'),
		array('sort_name'=>'TW', 'name'=>'TAIWAN, PROVINCE OF CHINA','code'=>'886'),
		array('sort_name'=>'TZ', 'name'=>'TANZANIA, UNITED REPUBLIC OF','code'=>'255'),
		array('sort_name'=>'UA', 'name'=>'UKRAINE','code'=>'380'),
		array('sort_name'=>'UG', 'name'=>'UGANDA','code'=>'256'),
		array('sort_name'=>'US', 'name'=>'UNITED STATES','code'=>'1'),
		array('sort_name'=>'UY', 'name'=>'URUGUAY','code'=>'598'),
		array('sort_name'=>'UZ', 'name'=>'UZBEKISTAN','code'=>'998'),
		array('sort_name'=>'VA', 'name'=>'HOLY SEE (VATICAN CITY STATE)','code'=>'39'),
		array('sort_name'=>'VC', 'name'=>'SAINT VINCENT AND THE GRENADINES','code'=>'1784'),
		array('sort_name'=>'VE', 'name'=>'VENEZUELA','code'=>'58'),
		array('sort_name'=>'VG', 'name'=>'VIRGIN ISLANDS, BRITISH','code'=>'1284'),
		array('sort_name'=>'VI', 'name'=>'VIRGIN ISLANDS, U.S.','code'=>'1340'),
		array('sort_name'=>'VN', 'name'=>'VIET NAM','code'=>'84'),
		array('sort_name'=>'VU', 'name'=>'VANUATU','code'=>'678'),
		array('sort_name'=>'WF', 'name'=>'WALLIS AND FUTUNA','code'=>'681'),
		array('sort_name'=>'WS', 'name'=>'SAMOA','code'=>'685'),
		array('sort_name'=>'XK', 'name'=>'KOSOVO','code'=>'381'),
		array('sort_name'=>'YE', 'name'=>'YEMEN','code'=>'967'),
		array('sort_name'=>'YT', 'name'=>'MAYOTTE','code'=>'262'),
		array('sort_name'=>'ZA', 'name'=>'SOUTH AFRICA','code'=>'27'),
		array('sort_name'=>'ZM', 'name'=>'ZAMBIA','code'=>'260'),
		array('sort_name'=>'ZW', 'name'=>'ZIMBABWE','code'=>'263')
  	   );
  	return $countryArray;
  }
?>